controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Login
app_connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

# Logout
# app_logout:
#     path: /logout

# Registration
app_inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

# Profile
app_profil:
    path: /profil
    controller: App\Controller\ProfilController::index
    # requirements:
    #     _role: 'ROLE_USER'